name: cron
on:
  schedule:
    # every five minutes
    # https://docs.github.com/en/actions/reference/events-that-trigger-workflows
    - cron: "*/5 * * * *"
jobs:
  crawl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Install Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add
          sudo apt-get install google-chrome-stable
          wget https://chromedriver.storage.googleapis.com/2.40/chromedriver_linux64.zip
          unzip ./chromedriver_linux64.zip
      - name: Run script
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          FACEBOOK_USERNAME: ${{ secrets.FACEBOOK_USERNAME }}
          FACEBOOK_PASSWORD: ${{ secrets.FACEBOOK_PASSWORD }}
        run: |
          python main.py
